import {
  ShoppingCart,
  Utensils,
  Coffee,
  Bus,
  Car,
  Fuel,
  SquareParking,
  Shirt,
  Smartphone,
  Sofa,
  Film,
  Gamepad2,
  Dumbbell,
  Zap,
  Droplet,
  Wifi,
  Phone,
  Home,
  Building,
  Stethoscope,
  Pill,
  Shell,
  ShieldPlus,
  Shield,
  BookOpen,
  GraduationCap,
  School,
  Plane,
  Bed,
  Scissors,
  Sparkles,
  WashingMachine,
  PawPrint,
  Gift,
  Repeat,
  type LucideIcon,
} from "lucide-react";

// Map icon names from config to actual Lucide components
export const iconMap: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  bus: Bus,
  car: Car,
  fuel: Fuel,
  "square-parking": SquareParking,
  shirt: Shirt,
  smartphone: Smartphone,
  sofa: Sofa,
  film: Film,
  "gamepad-2": Gamepad2,
  dumbbell: Dumbbell,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  phone: Phone,
  home: Home,
  building: Building,
  stethoscope: Stethoscope,
  pill: Pill,
  tooth: Shell, // Using Shell as placeholder for tooth
  "shield-plus": ShieldPlus,
  shield: Shield,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  school: School,
  plane: Plane,
  bed: Bed,
  scissors: Scissors,
  sparkles: Sparkles,
  "washing-machine": WashingMachine,
  "paw-print": PawPrint,
  gift: Gift,
  repeat: Repeat,
};

export function getCategoryIcon(iconName: string): LucideIcon | null {
  return iconMap[iconName] || null;
}
